### ISSUE TITLE
Font file path issues

### ISSUE THREAD

**Issue by goosehub** [FabianBeiner/PHP-Dummy-Image-Generator#1]
Including the font alongside the script does not always work. See the docs for imagettftext for fontfile here. http://php.net/manual/en/function.imagettftext.php.

It recommended this trick

```
// Set the enviroment variable for GD
putenv('GDFONTPATH=' . realpath('.'));

// Name the font to be used (note the lack of the .ttf extension)
$font = 'SomeFont';
```

Still, I'd recommend a note in the README since many people using this may not be aware they even need the font file or may need to place it in a different folder than the script because of the framework.

**Comment by FabianBeiner** [comment]
Only 1,5 years later, I fixed it! ;) Thanks.
